"""Enumerating possible purchase order statuses

Revision ID: f8751a9a1a0f
Revises: 75b8149d7906
Create Date: 2025-05-07 23:00:33.941397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8751a9a1a0f'
down_revision = '75b8149d7906'
branch_labels = None
depends_on = None

enum_name = 'purchase_order_status'
enum_values = ('pending', 'approved', 'shipped', 'received', 'cancelled')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
        ALTER TABLE purchase_orders
        ALTER COLUMN status
        TYPE {enum_name}
        USING status::{enum_name}
    """)

    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.execute("""
        ALTER TABLE purchase_orders
        ALTER COLUMN status
        TYPE VARCHAR(50)
        USING status::text
    """)

    # ### end Alembic commands ###
